export const SET_SELECT = 'SELECT/SET_SELECT'
export const SET_SELECT_COUNTRY = 'SELECT/SET_SELECT_COUNTRY'
export const SET_SELECT_LANGUAGE = 'SELECT/SET_SELECT_LANGUAGE'
export const SET_SELECT_SAVE = 'SELECT/SET_SELECT_SAVE'
export const SET_SELECT_FONT = 'SELECT/SET_SELECT_FONT'
export const SET_SELECT_FONT_SIZE = 'SELECT/SET_SELECT_FONT_SIZE'
export const SET_SELECT_PAGE_SIZE = 'SELECT/SET_SELECT_PAGE_SIZE'
export const SET_SELECT_TITLE = 'SELECT/SET_SELECT_TITLE'
export const SET_SELECT_PAGE_LOADER = 'SELECT/SET_SELECT_PAGE_LOADER'
export const SET_SWITCH = 'SWITCH/SET_SWITCH'

export const SET_BTN_QUICK = 'BUTTON/SET_BTN_QUICK'
export const SET_BTN_AUTO_LOAD = 'BUTTON/SET_BTN_AUTO_LOAD'
export const SET_BTN_AUTO = 'BUTTON/SET_BTN_AUTO'
export const SET_BTN_PROMPT = 'BUTTON/SET_BTN_PROMPT'
export const SET_BTN_WINDOW = 'BUTTON/SET_BTN_WINDOW'
export const SET_BTN_AD = 'BUTTON/SET_BTN_AD'
export const SET_BTN_HOT = 'BUTTON/SET_BTN_HOT'
export const SET_BTN_POSITION = 'BUTTON/SET_BTN_POSITION'

export const SET_TABS = 'TABS/SET_TABS'

export const SET_PLATE = 'PLATE/SET_PLATE'

export const SET_THEME = 'THEME/SET_THEME'
export const SET_THEME_CHANGE = 'THEME/SET_THEME_CHANGE'

export const SET_RANGE_SLIDER = 'SLIDER/SET_RANGE_SLIDER'

export const CREATE_VIDEO = 'VIDEO/CREATE_VIDEO'
export const SHOW_LOADER_VIDEO = 'VIDEO/SHOW_LOADER'
export const HIDE_LOADER_VIDEO = 'VIDEO/HIDE_LOADER'

export const CREATE_QUERY = 'QUERY/CREATE_QUERY'
export const SHOW_LOADER_QUERY = 'QUERY/SHOW_LOADER'
export const HIDE_LOADER_QUERY = 'QUERY/HIDE_LOADER'

export const REGISTRATION_REQUEST = 'AUTH/REGISTRATION_REQUEST'
export const REGISTRATION_SUCCESS = 'AUTH/REGISTRATION_SUCCESS'
export const REGISTRATION_FAILURE = 'AUTH/REGISTRATION_FAILURE'

export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'AUTH/LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'AUTH/LOGOUT_FAILURE'

export const SAVE_APP_STATE = 'APP/SAVE_APP_STATE'
